language: ruby
cache: bundler
before_install:
  - wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest
  - tar xfz dynamodb_local_latest
  - java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -inMemory -port 4567 &
rvm:
  - 2.1.0
  - 2.1.1
  - 2.1.2
notifications:
  slack: criff:sgthmc0fdH6cXbSy50Ncn1eV
