language: ruby
cache: bundler
before_script:
  - java -Djava.library.path=./spec/bin/dynamodb/DynamoDBLocal_lib/ -jar ./spec/bin/dynamodb/DynamoDBLocal.jar  -port 4567 -inMemory &
rvm:
  - 2.1.0
  - 2.1.1
  - 2.1.2
